### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by mrtn** [mariobehling/photocontest#1]
Hi,

For what drupal module is this app?

Best regards,
M

**Comment by mariobehling** [comment]
Hi, this was just a prototype. If you want to check out some work that is more advanced, please have a look here: https://github.com/phimpme/
There is also a Drupal with sample modules. (However Documentation is not so good, but if you know Drupal or one of the other CMS, it should work out.)

**Comment by mrtn** [comment]
Thank you, i will check.

**Comment by mrtn** [comment]
I have the Drupal website is running now.

When i check the app code, i see the app tries to login via http://MY_WEBSITE.COM/?q=phonegap_login

How does this work in drupal? I can t find any module code or drupal configuration that defines the phonegap_login url.

Can you explain this to me please?

**Comment by mariobehling** [comment]
Hi, as said this was only a prototype and we do not work on this anymore. Thank you.
